<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="welcome-PC" ignored="0" name="Validate Insurance" tests="1" failures="1" timestamp="07 Mar 2019 10:00:58 GMT" time="17.647" errors="0">
  <testcase name="feature" time="16.837" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: The following asserts failed:
	expected [Result for : V12UAA] but found [Sorry record not found]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: The following asserts failed:
expected [Result for : V12UAA] but found [Sorry record not found]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
Caused by: java.lang.AssertionError: The following asserts failed:
expected [Result for : V12UAA] but found [Sorry record not found]
at resources.Assertion.assert_result(Assertion.java:12)
at insuranceQA_VW.InsuranceCoverTest.validate_the_insurance_cover_start_date_and_end_date(InsuranceCoverTest.java:39)
at âœ½.Then Validate the Insurance cover Start date and End Date(InsuranceCover.feature:7)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Validate Insurance -->
